const TESTING_CONSTANTS = {
  TESTING_USER_USERNAME: process.env.TEST_USER_USERNAME ?? "test_user1",
  TESTING_USER_PASSWORD: process.env.TEST_USER_PASSWORD ?? "test_user1",
  TESTING_WEB_SERVER_PORT: 4001,
  TESTING_WEBSOCKET_SERVER_PORT: 5001,
  WEBSOCKET_UPDATE_DELAY_TIME: 17,
  FRAME_TIME: 1000 / 60
};

export { TESTING_CONSTANTS };
